# Generated by Django 5.2 on 2025-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="email_address",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
    ]
